### ISSUE TITLE
Add it to bar directly instead of behind more controls button

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/emojiconbini#1]
It looks like we can put the button on the actual bar instead of behind the more controls button.

See this issue in the Gutenberg repo:
https://github.com/WordPress/gutenberg/issues/14881

**Comment by Mamaduka** [comment]
@nickhamze did you get a chance to test the new toolbar button?

**Comment by nickhamze** [comment]
Yeah it looks and works great. I'll never hide anything behind the more controls button again.
