### ISSUE TITLE
Category buttons no longer work

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/emojiconbini#3]
I love it as a top level button. I was testing it this morning and I noticed that the category buttons at the top don't work anymore. Any idea why that would be? Other than that I think we are ready to launch.

**Comment by Mamaduka** [comment]
@nickhamze this might be the bug with Emoji Mart library. I'm able to reproduce the issue. Category buttons are working again after search is used.

I had to use super specific version of the library to avoid build errors. See https://github.com/missive/emoji-mart/issues/393.
