### ISSUE TITLE
Emoji display issues

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/emojiconbini#4]
It looks like the WordPress SVGs don't have all the emojis that Emoji mart does or they are named differently. For some of them they look like this. The broken image is the SVG that doesn't exist. 

<img width="288" alt="Screen Shot 2020-01-21 at 7 34 34 AM" src="https://user-images.githubusercontent.com/158918/72809142-ac909d00-3c20-11ea-8bcd-5adedd6d2c09.png">

**Comment by nickhamze** [comment]
For example, this sun emoji is trying to load:
https://s.w.org/images/core/emoji/12.0.0-1/svg/2600-fe0f.svg

but it should be trying to load:
https://s.w.org/images/core/emoji/12.0.0-1/svg/2600.svg

Maybe an easy fix is to remove everything after the "-" that seems to be the issue on all the ones I've found.

**Comment by Mamaduka** [comment]
@nickhamze that probably will fix the issue with `:sunny:` emoji and break others.

Female genie:
https://s.w.org/images/core/emoji/12.0.0-1/svg/1f9de-200d-2640-fe0f.svg

Male genie:
https://s.w.org/images/core/emoji/12.0.0-1/svg/1f9de.svg

So if I remove everything after first `-` user will always get male genie.

**Comment by nickhamze** [comment]
Ah, not sure what to do then :) .

**Comment by nickhamze** [comment]
Do you think maybe we could use these core files to generate the correct link for all emoji:
https://github.com/WordPress/WordPress/blob/5.3/wp-includes/js/wp-emoji.js
https://github.com/WordPress/WordPress/blob/5.3/wp-includes/js/twemoji.js

It's all greek to me but I thought I'd mention it.

**Comment by Mamaduka** [comment]
@nickhamze pushed the fix for this. I don't really like the method, but it does the job for now.
