### ISSUE TITLE
Enable Preview

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/emojiconbini#5]
Can we enable the preview (it looks kinda neat) but make it so the Emoji Mart text doesn't show.
<img width="360" alt="Screen Shot 2020-01-21 at 10 10 47 AM" src="https://user-images.githubusercontent.com/158918/72821636-63e3de80-3c36-11ea-8331-d57779921b2d.png">

```
.emoji-mart-title-label {
display:none;
}
```

**Comment by Mamaduka** [comment]
@nickhamze enabled preview and replaced the "Emoji Mart" text with "Emoji Conbini".
