### ISSUE TITLE
Update Emoji Mart to v3.0.0

### ISSUE THREAD

**Issue by Mamaduka** [sortabrilliant/emojiconbini#7]
Emoji Mart v3 was released a few days ago, it would be nice to update our dependency and maybe revisit some old issues.

Full changelog: https://github.com/missive/emoji-mart/blob/master/CHANGELOG.md#v300

**Comment by nickhamze** [comment]
sure, let's do that.

**Comment by Mamaduka** [comment]
@nickhamze updated Emoji Marto to v3. Unfortunately, this hasn't resolved our category issue (#3 ).

Everything else works like before. Should we tag this for WP 5.4 and push the new release as well?

**Comment by nickhamze** [comment]
@Mamaduka No worries, bump and push.

**Comment by Mamaduka** [comment]
Done ✅
